version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=apollo-task-secret
      - PORT=3000
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
